### ISSUE TITLE
How to participate?

### ISSUE THREAD

**Issue by g41797** [go-orb/go-orb#11]
Hi
I am looking for infrastructure projects to participate
my experience in go is a few months (see [home work](https://github.com/g41797/sputnik#readme))
in other languages more

**Comment by jochumdev** [comment]
Nice logo of sputnik!

Do you have the chance to join us on discord?

Brainstorming things you could start with:
- start with translating a Plugin from go-micro to go-orb (do not translate registry/etcd someone else is working on that).
- Read trough the code and add a "// TODO(g41797): needs more documentation"
- Ask any question's and make us think different
- HARD: Think about best ways to make go-orb fully/partly compatible with go-micro.dev/v4
- VERY HARD: implement broker
- WIP: when we colloberate well you could work on client/def/transport/{grpc,http,http2,http3,h2c}

Let me know if you found something, I'll take time to get you into this.
